name: ProyectoInterfazDefectoCorrea
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.3.0
  - aom=3.9.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cpuonly=2.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - double-conversion=3.3.1
  - expat=2.7.0
  - ffmpeg=7.1.1
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freeglut=3.2.2
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - harfbuzz=11.2.1
  - hdf5=1.14.6
  - icc_rt=2022.1.0
  - icu=75.1
  - idna=3.7
  - imath=3.1.12
  - intel-openmp=2023.1.0
  - jasper=4.2.5
  - jinja2=3.1.6
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libavif16=1.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=20.1.6
  - libcurl=8.14.1
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.22.5
  - libglib=2.84.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libogg=1.3.5
  - libopencv=4.11.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libusb=1.0.29
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.16
  - libxml2=2.13.8
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy-base=2.0.1
  - opencl-headers=2024.10.24
  - opencv=4.11.0
  - openexr=3.3.4
  - openh264=2.6.0
  - openjpeg=2.5.2
  - openssl=3.5.0
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.3
  - pcre2=10.45
  - pip=25.0
  - pixman=0.46.2
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pthreads-win32=2.9.1
  - pugixml=1.15
  - py-cpuinfo=9.0.0
  - py-opencv=4.11.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - qt6-main=6.8.3
  - rav1e=0.7.1
  - requests=2.32.3
  - scipy=1.15.3
  - sdl2=2.32.54
  - sdl3=3.2.16
  - seaborn=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - svt-av1=3.0.2
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - ultralytics=8.3.155
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.3
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - babel==2.17.0
      - joblib==1.5.0
      - numpy==2.2.5
      - pillow==11.2.1
      - pytz==2025.2
      - scikit-learn==1.6.1
      - threadpoolctl==3.6.0
      - tkcalendar==1.6.1
prefix: C:\Users\clark\anaconda3\envs\ProyectoInterfazDefectoCorrea
